TARGET = $(GITHUB_WORKSPACE)
TARGET_DIR = target/$(TARGET)/release
MSG = "Hello, World!"
NAME = "world"

.PHONEY: build
build:
  cargo build --release
	
.PHONEY: display
display:
	ls -l $(TARGET_DIR)
	echo $(MSG)
	echo $(NAME)