name: rust-toolchain
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      # Step 2: Set up dependencies (if needed)
      - name: Set up dependencies
        run: sudo apt update && sudo apt install -y build-essential

      # Step 3: Run the Makefile targets
      - name: Build the project
        run: make build

      - name: Run tests
        run: make test

      # Optional: Clean up files
      - name: Clean up
        run: make clean

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: check rust version
        run: |
          rustc --version
          cargo --version
          ls -l

      - name: Build
        run: cargo build
      # - name: Test
      #   run: cargo test
      # - name: Check
      #   run: cargo check
      # - name: Clippy
      #   run: cargo clippy -- -D warnings
      # - name: Format
      #   run: cargo fmt -- --check
      # - name: Doc
      #   run: cargo doc --no-deps
      # - name: Audit
      #   run: cargo audit
      # - name: Bench
      #   run: cargo bench
      # - name: Run
      #   run: cargo run
      # - name: Clean
      #   run: cargo clean

      - name: check yaml
        run: |
          ls -l
          cat output.yaml