name: rust-toolchain
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: workspace
        run: |
          ls -l
          echo "$pwd/hello"
          echo "${{ github.workspace }}"
          echo "$GITHUB_WORKSPACE"
          echo "$HOME"

      - name: run make for nadeem
        run: |
          make -C nadeem

      # Step 3: Run the Makefile targets
      - name: install rust
        run: \
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . $HOME/.cargo/env


      # - name: Set up Rust
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      #     override: true

      - name: check rust version
        run: |
          rustc --version
          cargo --version
          ls -la

      - name: Build
        run: cargo build
      # - name: Test
      #   run: cargo test
      # - name: Check
      #   run: cargo check
      # - name: Clippy
      #   run: cargo clippy -- -D warnings
      # - name: Format
      #   run: cargo fmt -- --check
      # - name: Doc
      #   run: cargo doc --no-deps
      # - name: Audit
      #   run: cargo audit
      # - name: Bench
      #   run: cargo bench
      # - name: Run
      #   run: cargo run
      # - name: Clean
      #   run: cargo clean

      - name: check yaml
        run: |
          ls -l
          cat output.yaml